### ISSUE TITLE
sec grado

### ISSUE THREAD

**Issue by FabioZTessitore** [christian99salerno/Helloworld#4]
Non serve a niente distinguere tra delta maggiore di zero e uguale a zero.

Poi devi fare dei controlli sui coefficienti come hai fatto con le eq di primo grado

**Comment by christian99salerno** [comment]
Va bene prof :(

**Comment by christian99salerno** [comment]
Ma perché devo fare i controlli sui coefficienti al massimo l'unico motivo sarebbe informare l'utente se si trova davanti a un'equazione pura spuria o completa

**Comment by FabioZTessitore** [comment]
come si comporta il programma se metti a=0, b=0, c=0?
perché li avevi fatti questi controlli nel caso delle equazioni di primo grado?

**Comment by christian99salerno** [comment]
Perché cambiava in quel caso l'equazione poteva essere impossibile o indeterminata

**Comment by christian99salerno** [comment]
In questo si deve eseguire sempre il delta e in base a quello si trovano le varie soluzioni

**Comment by FabioZTessitore** [comment]
ma se metti a=0, b=0, c=0 che delta calcoli? che soluzioni trovi

**Comment by christian99salerno** [comment]
Se a=0  è un'equazione di primo grado

**Comment by FabioZTessitore** [comment]
eh
devi considerare vari casi
se segui lo stesso schema delle eq di primo grado vai bene

**Comment by christian99salerno** [comment]
Va bene ci provo
